### PR TITLE
[trajoptlib] Make constraints use current and next index

### LINKED ISSUE #811: Make TrajoptLib kinematics use current and next variables instead of previous and current
The TrajoptLib kinematics constraints use previous and current variables: xₙ = xₙ₋₁ + vₙt + 1/2 aₙt².
```cpp
      problem.SubjectTo(x_n_1 + v_n * dt_sgmt + a_n * 0.5 * dt_sgmt * dt_sgmt ==
                        x_n);
```
It's using the wrong velocity and acceleration for that timestep. It should be xₙ = xₙ₋₁ + vₙ₋₁t + 1/2 aₙ₋₁t² instead, and ideally xₙ₊₁ = xₙ + vₙt + 1/2 aₙt² to follow common convention.

### PR DESCRIPTION
**Pull request by calcmogul**
Fixes #811.

### CODE REVIEW

**Comment by spacey-sooty** [comment]
This introduces a regression in differential generation. The straight line path passes on main.
[choreo-diagnostics-kj9Stldq.zip](https://github.com/user-attachments/files/17252838/choreo-diagnostics-kj9Stldq.zip)

**Comment by calcmogul** [comment]
On main, I get "locally infeasible" for that project's straight line path.

**Comment by spacey-sooty** [comment]
> I get "locally infeasible" for that project's straight line path on both main and this PR. Here's the solver output on main:
> 
> ```
> iter   time (ms)      error          cost       infeasibility
> =============================================================
>   40       0.263   1.575792e+01   7.871685e+01   1.022015e-01
> The problem is infeasible due to violated inequality constraints.
> Violated constraints (cᵢ(x) ≥ 0) in order of declaration:
>   8/297: -1.616065222258007e-06 ≥ 0
>   13/297: -2.663494520752877e-06 ≥ 0
>   23/297: -2.241180900109177e-08 ≥ 0
>   38/297: -6.995848632047105e-06 ≥ 0
>   48/297: -1.5678674351732313e-06 ≥ 0
> ```

Ah yep nvm it was passing on beta 2 we've introduced a regression somewhere betweeen there and here. Interesting because I thought I tested differential stuff for https://github.com/SleipnirGroup/Choreo/pull/821 and a similar path was passing

**Review by spacey-sooty — APPROVED** [review]
Tested and seems fine

**Comment by calcmogul** [comment]
Beta 2 also works for me, and the commit right after beta 2 has feasibility restoration converge to a locally infeasible point.
```
commit 3c0603a8037815a4924e1dc0f7f6697266a8a4ae
Author: bruingineer <joshua.g.camarena@gmail.com>
Date:   Wed Oct 2 20:40:06 2024 -0700

    [trajoptlib] Make GetIndex() usage consistent and fix GetIndex() (#820)
```

**Pull request merged**
