### PR TITLE
[docs] Fix requirements.txt

### PR DESCRIPTION
**Pull request by bryceroethel**
`requirements.txt` was in the wrong directory, and also included an invalid package (originally `mkdocs-materials`, correct package name is `mkdocs-material`). Also added instructions for building API docs. Didn't get a chance to leave a comment on the original PR before it was merged.

### CODE REVIEW

**Comment by bryceroethel** [comment]
Would it be reasonable for CI to utilize `requirements.txt` or should it be left as is?

**Comment by spacey-sooty** [comment]
> Would it be reasonable for CI to utilize `requirements.txt`

yes

**Review by oh-yes-0-fps — APPROVED** [review]

**Comment by bryceroethel** [comment]
Didn't change the name of the cache, let me know if it should be updated

**Comment by spacey-sooty** [comment]
seems fine

**Review by spacey-sooty — APPROVED** [review]

**Pull request merged**
