### PR TITLE
Replace circle heading handle with triangle

### PR DESCRIPTION
**Pull request by Nsl106**
Intended to fix https://github.com/SleipnirGroup/Choreo/issues/341, just a simple change to make the heading handle on waypoints a triangle so the front of the robot is more clear.
347597606-8313d2f9-c9e3-48a2-8fa5-275f67db9b0c

### CODE REVIEW

**Comment by calcmogul** [comment]
The clickable area feels too small with a side length of 0.2. A side length of 0.25 gives equivalent area:
```
circle area = triangle area
πr² = 1/2 l²
2πr² = l²
l = √(2πr²)
l = r√(2π)
l = 0.1 √(2π)
l = 0.25066
l ≈ 0.25
```

**Review by calcmogul — CHANGES_REQUESTED** [review]
The clickable area feels too small with a side length of 0.2. A side length of 0.26935 gives equivalent area:
```
triangle area = circle area
1/2 bh = πr²
1/2 l √3/2 l = πr²
√3/4 l² = πr²
l² = 4πr²/√3
l = √(4πr²/√3)
l = 2r√(π/√3)
l = 2 * 0.1 √(π/√3)
l ≈ 0.26935
```

**Review by calcmogul — CHANGES_REQUESTED** [review]
The triangle point math in render() checks out.

The white circle on the playback robot needs to be changed to a triangle. I think it's rendered in InterpolatedRobot.tsx.
Screenshot_20240711_124026

**Comment by shueja** [comment]
> The triangle point math in render() checks out.
> 
> The white circle on the playback robot needs to be changed to a triangle, but idk where that's rendered. Screenshot_20240711_124026

**Comment by shueja** [comment]
The playback robot is InterpolatedRobot.tsx.

**Comment by Nsl106** [comment]
Where should the shared code between them go? Or would it be better to just copy-paste the same math from OverlayWaypoint.tsx? Also thanks for cleaning up the math comments :)

**Comment by calcmogul** [comment]
It's not that much code, so I think it's fine to copy-paste.

**Comment by Nsl106** [comment]
What would you think about making the center circle a triangle or arrow (similar to the advantagescope odometry page), and making the heading handle only be visible when the waypoint is selected?

**Comment by calcmogul** [comment]
> making the heading handle only be visible when the waypoint is selected

That makes it less clear how you're supposed to interact with a pose waypoint.

**Comment by Nsl106** [comment]
It could just be if you grab it anywhere but the heading handle, not sure if that would be clear enough though.

**Comment by calcmogul** [comment]
Having the waypoint translate if you missed the rotation handle sounds frustrating.

**Review by calcmogul — APPROVED** [review]

**Pull request merged**
