### PR TITLE
[choreo] [trajoptlib] Use more robust time estimates for intervals and initial dt decision variable

### PR DESCRIPTION
**Pull request by bruingineer**
blocked by #820

### CODE REVIEW

**Comment by shueja** [comment]
I can't fully test this until tomorrow, but looks logically correct.

**Comment by spacey-sooty** [comment]
From my testing this has introduced a regression into the Differential generation (it can no longer generate a straight line path)

**Comment by bruingineer** [comment]
I think the kinematics for differential generator need to get looked at.

**Comment by spacey-sooty** [comment]
> I think the kinematics for differential generator need to get looked at.

The differential generator is fundamentally broken, but this PR caused a regression on top of that

**Review by spacey-sooty — APPROVED** [review]
Regressions appears to be gone

**Pull request merged**
