### PR TITLE
Replace no-args trigger factories(done(), active(), running(), etc.) with public properties

### PR DESCRIPTION
**Pull request by Daniel1464**
Resolves https://github.com/SleipnirGroup/Choreo/issues/897

Since these triggers are used so often, they can help significantly reduce clutter in the code.
Before:
```
path1.done().onTrue(...)
path2.active().onTrue(...)
```
Now:
```
path1.done.onTrue(...)
path2.active.onTrue(...)
```
This also reduces the number of allocations.

### CODE REVIEW

**Comment by Daniel1464** [comment]
Btw am working on c++ implementation soon; just kinda busy this week

**Review by spacey-sooty — CHANGES_REQUESTED** [review]
This needs to update documentation as well

**Comment by oh-yes-0-fps** [comment]
This should not be done, if you want to reduce allocations keep them stored as members internally.

Having access be a method is more flexible allowing for extra arguments, there really isn't a benefit to doing it like this besides removing the parent which isn't worth it for giving up coherency with the rest of the API.

**Comment by spacey-sooty** [comment]
This restricts us in terms of future API changes so we won't do it but if you'd like to make these functions singletons that would be accepted

**Comment by Daniel1464** [comment]
> Having access be a method is more flexible allowing for extra arguments, there really isn't a benefit to doing it like this besides removing the parent which isn't worth it for giving up coherency with the rest of the API.

I dont think this stops us from adding method overloads of done(), active(), etc if we need them to accept extra arguments. 

Having no-args methods be replaced by properties is also pretty consistent as well. In general, I think that if we don't need something to be a method it should not be a method, and it should be properly represented as what it is.

**Comment by spacey-sooty** [comment]
> > Having access be a method is more flexible allowing for extra arguments, there really isn't a benefit to doing it like this besides removing the parent which isn't worth it for giving up coherency with the rest of the API.
> 
> I dont think this stops us from adding a done()/active() method that takes in arguments.
> 
> Having no-args methods be replaced by properties is also pretty consistent as well. In general, I think that if we don't need something to be a method it should not be a method, and it should be properly represented as what it is.

The issue with this is it makes it very hard to change the implementation of these Triggers without breaking the API. With a method this is reduced.

**Comment by Daniel1464** [comment]
> The issue with this is it makes it very hard to change the implementation of these Triggers without breaking the API. With a method this is reduced.

ok honestly u guys prob have more foresight than me on this, so i'll trust your intuition.

**Pull request closed without merging**
