### PR TITLE
[trajoptlib] Build: add CMakePresets.json for default CMake configs

### PR DESCRIPTION
**Pull request by spacey-sooty**
Also add CMakeUserPresets.json to .gitignore

### CODE REVIEW

**Comment by spacey-sooty** [comment]
Huh this doesn't fail locally...

**Comment by calcmogul** [comment]
The first error seems to be from CI not having Ninja installed.

**Comment by spacey-sooty** [comment]
Its always windows :roll_eyes:

**Comment by spacey-sooty** [comment]
this must be some bug or something pnpm run fmt removes this locally but it fails the build here

**Review by shueja — APPROVED** [review]

**Pull request merged**
